<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>scanmatcher</name>
  <version>0.0.0</version>
  <description>scan-matching package</description>
  <maintainer email="rsasaki0109@gmail.com">sasaki</maintainer>
  <license>BSD-2-Clause</license>

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Build deps (compile-time) -->
  <build_depend>rclcpp</build_depend>
  <build_depend>rclcpp_components</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>tf2_ros</build_depend>
  <build_depend>tf2_sensor_msgs</build_depend>
  <build_depend>tf2_geometry_msgs</build_depend>
  <build_depend>tf2_eigen</build_depend>
  <build_depend>pcl_conversions</build_depend>
  <build_depend>pcl_msgs</build_depend>
  <build_depend>lidarslam_msgs</build_depend>
  <build_depend>ndt_omp_ros2</build_depend>

  <!-- System libs via rosdep -->
  <build_depend>libpcl-dev</build_depend>
  <build_depend>opencv</build_depend>
  <build_depend>libg2o-dev</build_depend>

  <!-- Exec deps (runtime) -->
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>tf2_sensor_msgs</exec_depend>
  <exec_depend>tf2_geometry_msgs</exec_depend>
  <exec_depend>tf2_eigen</exec_depend>
  <exec_depend>pcl_conversions</exec_depend>
  <exec_depend>pcl_msgs</exec_depend>
  <exec_depend>lidarslam_msgs</exec_depend>
  <exec_depend>ndt_omp_ros2</exec_depend>

  <!-- System libs at runtime -->
  <exec_depend>libpcl-dev</exec_depend>
  <exec_depend>opencv</exec_depend>
  <exec_depend>libg2o-dev</exec_depend>

  <!-- Test deps -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
